#!/bin/bash
# Use shipwright to build and tag all the images in the images folder.

readonly ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

shipwright() {
    # Build using Shipwright
    docker run --rm \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v $HOME/.docker:/root/.docker \
           -v $ROOT:$ROOT \
           -w $ROOT \
           nigelgbanks/shipwright:latest shipwright "$@"
}

main () {
    if hash docker-machine &>/dev/null; then
        $ROOT/commands/cache-clear
        shipwright
    fi
}
main "$@"
